"""Create items table

Revision ID: 24f187cef0c2
Revises: 604d727e041a
Create Date: 2023-11-12 01:47:12.606121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24f187cef0c2'
down_revision: Union[str, None] = '604d727e041a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('items', 'descripttion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('descripttion', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('items', 'description')
    # ### end Alembic commands ###
