"""Create items table

Revision ID: 604d727e041a
Revises: 4f77f636897e
Create Date: 2023-11-12 01:36:25.816500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '604d727e041a'
down_revision: Union[str, None] = '4f77f636897e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'descripttion',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'descripttion',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
